---
abstract: 'Encode/Decode Values In A Structure'
author:
  - 'Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Visitor-Encode
no_index:
  directory:
    - inc
    - t
requires:
  Data::Visitor: 0.26
  Encode: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10006
