abstract: Encode/Decode Values In A Structure
author: Daisuke Maki <daisuke@endeworks.jp<gt>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Data-Visitor-Encode
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::Visitor: 0
  Encode: 0
version: 0.01
